base_url = "https://marcoh.dev"
title = "Marco Herrera-Rendon"
description = "Software Engineer"
default_language = "en"

[extra]
author = "Marco Herrera-Rendon"
bio = "Writing about systems programming, engineering architecture, and minimalist design."
github = "https://github.com/mherrerarendon"
linkedin = "https://linkedin.com/in/marcoherrerarendon"
